linters:
  enable-all: yes
  disable:
    - cyclop
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - interfacer
    - lll
    - maligned
    - nakedret
    - nlreturn
    - noctx
    - paralleltest
    - prealloc
    - scopelint
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  revive:
    rules:
      # golint
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: increment-decrement
      - name: package-comments
      - name: range
      - name: time-naming
      - name: unexported-return
      - name: var-declaration
      # extras
      - name: atomic
      - name: bool-literal-in-expr
      - name: call-to-gc
      - name: confusing-naming
      - name: confusing-results
      - name: constant-logical-expr
      - name: defer
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: get-return
      - name: identical-branches
      - name: if-return
      - name: import-shadowing
      - name: imports-blacklist
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: nested-structs
      - name: range-val-address
      - name: range-val-in-closure
      - name: redefines-builtin-id
      - name: string-format
      - name: string-of-int
      - name: struct-tag
      - name: superfluous-else
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      - name: useless-break
      - name: waitgroup-by-value
      - name: receiver-naming
        disabled: yes
      - name: indent-error-flow
        disabled: yes
      - name: blank-imports
        disabled: yes

  stylecheck:
    checks:
      - '-ST1006'
